"""Initial migration

Revision ID: 8c15ccc27525
Revises: 
Create Date: 2026-09-22 04:23:48.583556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c15ccc27525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variant_a_name', sa.String(length=100), nullable=False),
    sa.Column('variant_b_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ab_experiments_id'), 'ab_experiments', ['id'], unique=False)
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisers_id'), 'advertisers', ['id'], unique=False)
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_content_categories_id'), 'content_categories', ['id'], unique=False)
    op.create_index(op.f('ix_content_categories_slug'), 'content_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ab_test_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=10), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("variant IN ('A', 'B')", name='chk_variant'),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'user_id', name='uq_experiment_user')
    )
    op.create_index('idx_ab_experiment', 'ab_test_assignments', ['experiment_id'], unique=False)
    op.create_index('idx_ab_user', 'ab_test_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_ab_test_assignments_id'), 'ab_test_assignments', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('budget > 0', name='chk_campaign_budget'),
    sa.CheckConstraint('end_date >= start_date', name='chk_campaign_dates'),
    sa.CheckConstraint('spent >= 0', name='chk_campaign_spent'),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_active', 'campaigns', ['is_active'], unique=False)
    op.create_index('idx_campaigns_advertiser', 'campaigns', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('popularity_score >= 0.0 AND popularity_score <= 1.0', name='chk_content_popularity'),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_active', 'content', ['is_active'], unique=False)
    op.create_index('idx_content_category', 'content', ['category_id'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('affinity_score', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('affinity_score >= 0.0 AND affinity_score <= 1.0', name='chk_affinity_score'),
    sa.CheckConstraint('interaction_count >= 0', name='chk_interaction_count'),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category')
    )
    op.create_index('idx_user_interests_user', 'user_interests', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='chk_session_duration'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_started', 'user_sessions', ['started_at'], unique=False)
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('target_category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('frequency_cap', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bid_amount > 0', name='chk_bid_amount'),
    sa.CheckConstraint('frequency_cap > 0', name='chk_frequency_cap'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ads_active', 'advertisements', ['is_active'], unique=False)
    op.create_index('idx_ads_campaign', 'advertisements', ['campaign_id'], unique=False)
    op.create_index('idx_ads_category', 'advertisements', ['target_category_id'], unique=False)
    op.create_index(op.f('ix_advertisements_id'), 'advertisements', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('APP_OPEN', 'SEARCH', 'CONTENT_VIEW', 'CONTENT_LIKE', 'CONTENT_DISLIKE', 'AD_IMPRESSION', 'AD_CLICK', 'AD_SKIP', 'SESSION_START', 'SESSION_END')", name='chk_event_type'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_created', 'events', ['created_at'], unique=False)
    op.create_index('idx_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_events_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_user_id', 'events', ['user_id'], unique=False)
    op.create_index('idx_events_user_type', 'events', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('ad_impressions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impressions_ad', 'ad_impressions', ['ad_id'], unique=False)
    op.create_index('idx_impressions_created', 'ad_impressions', ['created_at'], unique=False)
    op.create_index('idx_impressions_user', 'ad_impressions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ad_impressions_id'), 'ad_impressions', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('was_shown', sa.Boolean(), nullable=True),
    sa.Column('was_clicked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_algorithm', 'recommendations', ['algorithm'], unique=False)
    op.create_index('idx_recommendations_user', 'recommendations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('ad_clicks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('impression_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['impression_id'], ['ad_impressions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clicks_ad', 'ad_clicks', ['ad_id'], unique=False)
    op.create_index('idx_clicks_created', 'ad_clicks', ['created_at'], unique=False)
    op.create_index('idx_clicks_user', 'ad_clicks', ['user_id'], unique=False)
    op.create_index(op.f('ix_ad_clicks_id'), 'ad_clicks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_clicks_id'), table_name='ad_clicks')
    op.drop_index('idx_clicks_user', table_name='ad_clicks')
    op.drop_index('idx_clicks_created', table_name='ad_clicks')
    op.drop_index('idx_clicks_ad', table_name='ad_clicks')
    op.drop_table('ad_clicks')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index('idx_recommendations_user', table_name='recommendations')
    op.drop_index('idx_recommendations_algorithm', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ad_impressions_id'), table_name='ad_impressions')
    op.drop_index('idx_impressions_user', table_name='ad_impressions')
    op.drop_index('idx_impressions_created', table_name='ad_impressions')
    op.drop_index('idx_impressions_ad', table_name='ad_impressions')
    op.drop_table('ad_impressions')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('idx_events_user_type', table_name='events')
    op.drop_index('idx_events_user_id', table_name='events')
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_entity', table_name='events')
    op.drop_index('idx_events_created', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_advertisements_id'), table_name='advertisements')
    op.drop_index('idx_ads_category', table_name='advertisements')
    op.drop_index('idx_ads_campaign', table_name='advertisements')
    op.drop_index('idx_ads_active', table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_sessions_started', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_index('idx_user_interests_user', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index('idx_content_category', table_name='content')
    op.drop_index('idx_content_active', table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_advertiser', table_name='campaigns')
    op.drop_index('idx_campaigns_active', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_ab_test_assignments_id'), table_name='ab_test_assignments')
    op.drop_index('idx_ab_user', table_name='ab_test_assignments')
    op.drop_index('idx_ab_experiment', table_name='ab_test_assignments')
    op.drop_table('ab_test_assignments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_content_categories_slug'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_id'), table_name='content_categories')
    op.drop_table('content_categories')
    op.drop_index(op.f('ix_advertisers_id'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_ab_experiments_id'), table_name='ab_experiments')
    op.drop_table('ab_experiments')
    # ### end Alembic commands ###
